server:
  port: 9527




eureka:
  client:
    # 是否将自己注册进Eureka Server默认为true
    register-with-eureka: true
    # 表示是否从Eureka Server抓取已注册信息，默认为true。单节点无所谓，集群必须设置为true。
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 从路由中心开启路由
          enabled: true
      routes:
        - id: payment_route
#          uri: http://localhost:8001
          # 地址替换成服务名
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   # 断言： 路径匹配才能访问
            - After=2020-05-09T22:45:49.859+08:00[Asia/Shanghai] # 断言 请求位于这个时间后
            # Cookie 需要两个参数，一个是cookie name，一个是正则表达式